// backend/src/picky/picky.aliases.ts
export const PICKY_ALIASES: Record<string, string[]> = {
  // ===== 글로벌 스튜디오/배급/레이블 =====
  디즈니: ['Disney', 'Walt Disney', 'Disney Animation', 'Disney+'],
  픽사: ['Pixar'],
  마블: ['Marvel', 'Marvel Studios', 'MCU', 'Avengers'],
  루카스필름: ['Lucasfilm', 'Star Wars'],
  스타워즈: ['Star Wars', 'Lucasfilm'],
  '20세기폭스': ['20th Century', '20th Century Studios', '20th Century Fox'],
  서치라이트: ['Searchlight Pictures', 'Searchlight'],
  유니버설: ['Universal Pictures', 'Universal'],
  일루미네이션: ['Illumination', 'Illumination Entertainment', 'Minions'],
  드림웍스: ['DreamWorks', 'DreamWorks Animation'],
  워너: ['Warner Bros.', 'Warner Bros', 'WB'],
  디씨: ['DC', 'DC Studios', 'Warner Bros.'],
  파라마운트: ['Paramount', 'Paramount Pictures'],
  MGM: ['MGM', 'Metro-Goldwyn-Mayer'],
  소니픽처스: ['Sony Pictures', 'Sony'],
  콜럼비아: ['Columbia Pictures', 'Columbia'],
  트라이스타: ['TriStar Pictures', 'TriStar'],
  라이언스게이트: ['Lionsgate'],
  A24: ['A24'],
  블룸하우스: ['Blumhouse', 'Blumhouse Productions'],
  레전더리: ['Legendary', 'Legendary Pictures'],
  미라맥스: ['Miramax'],
  폭스서치라이트: ['Searchlight Pictures'],
  포커스피처스: ['Focus Features'],
  뉴라인: ['New Line Cinema'],
  HBO: ['HBO', 'HBO Max', 'Max'],
  넷플릭스: ['Netflix'],
  아마존: ['Amazon', 'Amazon Studios', 'Prime Video'],
  애플TV: ['Apple TV+', 'Apple TV Plus', 'Apple'],
  파라마운트플러스: ['Paramount+', 'Paramount Plus'],
  훌루: ['Hulu'],
  피콕: ['Peacock'],
  스카이: ['Sky', 'Sky Studios'],
  BBC: ['BBC', 'BBC One', 'BBC Two'],

  // ===== 애니/스튜디오(일본 중심) =====
  지브리: ['Studio Ghibli', 'Ghibli', '미야자키', 'Miyazaki'],
  토에이: ['Toei Animation', 'Toei'],
  선라이즈: ['Sunrise', 'Bandai Namco Filmworks'],
  매드하우스: ['Madhouse'],
  마파: ['MAPPA'],
  본즈: ['Bones', 'Studio Bones'],
  교토애니: ['Kyoto Animation', 'KyoAni'],
  유포터블: ['ufotable'],
  트리거: ['TRIGGER', 'Studio Trigger'],
  피에로: ['Pierrot', 'Studio Pierrot'],
  '프로덕션 I.G': ['Production I.G', 'Production IG'],
  위트스튜디오: ['Wit Studio', 'WIT'],
  A1: ['A-1 Pictures', 'A1 Pictures'],
  클로버웍스: ['CloverWorks'],
  JCS: ['J.C. Staff', 'JC Staff'],
  TMS: ['TMS Entertainment'],
  샤프트: ['Shaft'],
  화이트폭스: ['White Fox'],
  PWORKS: ['P.A. Works', 'PA Works'],
  실버링크: ['SILVER LINK.'],
  키네마시트러스: ['Kinema Citrus'],
  사이언스사루: ['Science SARU'],
  리덴필름: ['LIDENFILMS', 'Liden Films'],
  스튜디오딘: ['Studio Deen'],
  브레인즈베이스: ["Brain's Base"],
  스튜디오컬러리도: ['Studio Colorido'],
  오엘엠: ['OLM'],
  '8bit': ['8bit'],
  엔지: ['ENGI'],
  데이비드프로덕션: ['David Production'],
  코믹스웨이브: ['CoMix Wave Films', 'Comix Wave'],
  타입문: ['Type-Moon', 'Fate'],
  곤조: ['Gonzo'],
  XEBEC: ['XEBEC'],
  AIC: ['AIC'],
  GAINAX: ['GAINAX'],

  // ===== 한국 제작/방송/스튜디오(검색어 확장용) =====
  스튜디오드래곤: ['Studio Dragon', 'tvN', 'CJ ENM'],
  CJENM: ['CJ ENM', 'tvN'],
  tvN: ['tvN'],
  JTBC: ['JTBC'],
  SBS: ['SBS'],
  KBS: ['KBS'],
  MBC: ['MBC'],
  티빙: ['TVING', 'CJ ENM'],
  웨이브: ['Wavve'],
  쿠팡플레이: ['Coupang Play'],
  왓챠: ['Watcha'],
  디즈니플러스: ['Disney+', 'Disney Plus'],
  넷플릭스오리지널: ['Netflix', 'Netflix Original'],

  // ===== 대표 프랜차이즈/세계관 =====
  해리포터: ['Harry Potter', 'Wizarding World', 'Hogwarts'],
  반지의제왕: ['The Lord of the Rings', 'LOTR', 'Middle-earth'],
  호빗: ['The Hobbit', 'Middle-earth'],
  스타트렉: ['Star Trek'],
  미션임파서블: ['Mission: Impossible', 'Mission Impossible'],
  분노의질주: ['Fast & Furious', 'Fast and Furious'],
  트랜스포머: ['Transformers'],
  쥬라기: ['Jurassic Park', 'Jurassic World'],
  터미네이터: ['Terminator'],
  에일리언: ['Alien'],
  프레데터: ['Predator'],
  인디아나존스: ['Indiana Jones'],
  본시리즈: ['Bourne'],
  '007': ['James Bond', '007'],
  배트맨: ['Batman', 'DC'],
  슈퍼맨: ['Superman', 'DC'],
  스파이더맨: ['Spider-Man', 'Spiderman', 'Marvel'],
  아이언맨: ['Iron Man', 'Marvel'],
  캡틴아메리카: ['Captain America', 'Marvel'],
  토이스토리: ['Toy Story', 'Pixar'],
  겨울왕국: ['Frozen', 'Disney'],
  모아나: ['Moana', 'Disney'],
  인사이드아웃: ['Inside Out', 'Pixar'],
  코코: ['Coco', 'Pixar'],
  라푼젤: ['Tangled', 'Disney'],
  알라딘: ['Aladdin', 'Disney'],
  라이온킹: ['The Lion King', 'Disney'],
  주토피아: ['Zootopia', 'Disney'],
  빅히어로: ['Big Hero 6', 'Disney'],
  슈렉: ['Shrek', 'DreamWorks'],
  드래곤길들이기: ['How to Train Your Dragon', 'DreamWorks'],
  쿵푸팬더: ['Kung Fu Panda', 'DreamWorks'],
  미니언즈: ['Minions', 'Illumination'],

  // ===== 애니 대표 타이틀(키워드/콜렉션 검색 보강용) =====
  원피스: ['One Piece', 'Toei Animation'],
  드래곤볼: ['Dragon Ball', 'Toei Animation'],
  나루토: ['Naruto', 'Pierrot'],
  블리치: ['Bleach', 'Pierrot'],
  귀멸의칼날: ['Demon Slayer', 'Kimetsu no Yaiba', 'ufotable'],
  주술회전: ['Jujutsu Kaisen', 'MAPPA'],
  진격의거인: ['Attack on Titan', 'Wit Studio', 'MAPPA'],
  에반게리온: ['Evangelion', 'GAINAX', 'Studio Khara'],
  사이버펑크: ['Cyberpunk: Edgerunners', 'TRIGGER'],
  스즈메: ['Suzume', 'Makoto Shinkai', 'CoMix Wave'],
  너의이름은: ['Your Name', 'Kimi no Na wa', 'Makoto Shinkai'],
  날씨의아이: ['Weathering with You', 'Makoto Shinkai'],

  // ===== 추가로 많이 쓰는 키워드(무드/장르 보강용) =====
  디즈니감성: [
    'family',
    'fairy tale',
    'musical',
    'princess',
    'heartwarming',
    'Disney',
  ],
  힐링: ['healing', 'heartwarming', 'feel good'],
  가족: ['family', 'kids', 'all ages'],
  동화: ['fairy tale', 'storybook', 'magic'],
  음악: ['musical', 'music'],
  판타지: ['fantasy', 'magic'],
  모험: ['adventure'],
  로맨스: ['romance'],
  성장: ['coming of age', 'teen', 'youth'],
  감성: ['emotional', 'touching', 'bittersweet'],
};
