// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generate-footer-notices.cjs

export type FooterNoticeItem = {
  date: string;
  title: string;
  body: string;
};

export type FooterDeveloperNoteItem = {
  hash: string;
  date: string;
  title: string;
  body: string;
};

export const NOTICE_ITEMS: FooterNoticeItem[] = [
  { date: "2026-03-06", title: "서비스 안내: 푸시 알림 점검 예정", body: "더 안정적인 알림 제공을 위해 알림 시스템 점검을 진행할 예정입니다." },
  { date: "2026-02-25", title: "이용 안내: 추천 결과 정확도 개선", body: "검색어와 취향 기반 추천 결과의 일관성을 높이기 위한 업데이트를 반영했습니다." },
  { date: "2026-02-12", title: "서비스 안내: 일부 페이지 로딩 개선", body: "메인 화면과 상세 페이지의 초기 로딩 속도를 개선했습니다." },
  { date: "2026-01-30", title: "정책 안내: 데이터 출처 고지 강화", body: "외부 데이터/API 사용 내역을 더 쉽게 확인할 수 있도록 고지 영역을 보강했습니다." },
];

export const DEVELOPER_NOTE_ITEMS: FooterDeveloperNoteItem[] = [
  { hash: "8c7054e", date: "2026-03-11", title: "서비스 업데이트: desktop 작업본 반영", body: "desktop 작업본 반영 관련 업데이트를 반영했습니다." },
  { hash: "b6dad78", date: "2026-03-06", title: "기능 업데이트: 분석하기 기능 활성 / header/footer ux ui 수정 / 설정 페이지 활성", body: "분석하기 기능 활성 / header/footer ux ui 수정 / 설정 페이지 활성 관련 업데이트를 반영했습니다." },
  { hash: "88eb30c", date: "2026-02-09", title: "문서 업데이트: README 업데이트", body: "README 업데이트 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "00496f9", date: "2026-02-09", title: "디자인 개선: footer 구조 개선 및 픽무비 공통 색상 변경", body: "footer 구조 개선 및 픽무비 공통 색상 변경 관련 업데이트를 반영했습니다." },
  { hash: "2e360fb", date: "2026-02-08", title: "기능 업데이트: 추천 관련 코드 검색 코드로 이관 및 속도 개선 진행", body: "추천 관련 코드 검색 코드로 이관 및 속도 개선 진행 관련 업데이트를 반영했습니다." },
  { hash: "fa181ff", date: "2026-02-08", title: "기능 업데이트: 공통 필터 정리", body: "공통 필터 정리 관련 업데이트를 반영했습니다." },
  { hash: "c801b22", date: "2026-02-08", title: "디자인 개선: 찜/플레이리스트 UX UI 개선", body: "찜/플레이리스트 UX UI 개선 관련 업데이트를 반영했습니다." },
  { hash: "7153bcc", date: "2026-02-08", title: "디자인 개선: Footer에 적용되는 디자인 수정", body: "Footer에 적용되는 디자인 수정 관련 업데이트를 반영했습니다." },
  { hash: "f6c809d", date: "2026-02-08", title: "기능 업데이트: 백엔드 클론 성능 개선 및 구조 개선", body: "백엔드 클론 성능 개선 및 구조 개선 관련 업데이트를 반영했습니다." },
  { hash: "7e846c6", date: "2026-02-08", title: "기능 업데이트: 찜/플레이리스트 개선 및 박스오피스 오류 수정", body: "찜/플레이리스트 개선 및 박스오피스 오류 수정 관련 업데이트를 반영했습니다." },
  { hash: "aa95fa5", date: "2026-02-01", title: "디자인 개선: 프라임비디오 추가", body: "프라임비디오 추가 관련 업데이트를 반영했습니다." },
  { hash: "091ca97", date: "2026-02-01", title: "기능 업데이트: 상세페이지 출시년도 개선", body: "상세페이지 출시년도 개선 관련 업데이트를 반영했습니다." },
  { hash: "ed2f8eb", date: "2026-02-01", title: "기능 업데이트: 메인페이지 개선", body: "메인페이지 개선 관련 업데이트를 반영했습니다." },
  { hash: "0151b52", date: "2026-01-22", title: "기능 업데이트: 찜/플레이리스트 구조 개선 진행", body: "찜/플레이리스트 구조 개선 진행 관련 업데이트를 반영했습니다." },
  { hash: "4902fe1", date: "2026-01-21", title: "디자인 개선: 간단한 css 수정", body: "간단한 css 수정 관련 업데이트를 반영했습니다." },
  { hash: "fc7e8af", date: "2026-01-21", title: "기능 업데이트: 상세페이지 페이지 이동 및 디자인 개선", body: "상세페이지 페이지 이동 및 디자인 개선 관련 업데이트를 반영했습니다." },
  { hash: "c335b4c", date: "2026-01-21", title: "기능 업데이트: 콘텐츠 정보 개선", body: "콘텐츠 정보 개선 관련 업데이트를 반영했습니다." },
  { hash: "3d3cf5b", date: "2026-01-20", title: "디자인 개선: 내 찜 캐러셀 디자인 수정", body: "내 찜 캐러셀 디자인 수정 관련 업데이트를 반영했습니다." },
  { hash: "d794c34", date: "2026-01-20", title: "기능 업데이트: 상세 페이지 css 개선 및 콘텐츠 정보 개선", body: "상세 페이지 css 개선 및 콘텐츠 정보 개선 관련 업데이트를 반영했습니다." },
  { hash: "fdc47b2", date: "2026-01-20", title: "기능 업데이트: 콘텐츠 정보 백엔드 전환 및 상세페이지 개선", body: "콘텐츠 정보 백엔드 전환 및 상세페이지 개선 관련 업데이트를 반영했습니다." },
  { hash: "d87cb91", date: "2026-01-15", title: "기능 업데이트: 백엔드 콘텐츠 정보 추가", body: "백엔드 콘텐츠 정보 추가 관련 업데이트를 반영했습니다." },
  { hash: "d39bf31", date: "2026-01-12", title: "문서 업데이트: README.MD 수정", body: "README.MD 수정 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "83e9e0d", date: "2026-01-12", title: "문서 업데이트: README.MD 수정", body: "README.MD 수정 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "d54998f", date: "2026-01-12", title: "문서 업데이트: README.MD 작성", body: "README.MD 작성 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "7e741d2", date: "2026-01-12", title: "기능 업데이트: 오류 및 성능 개선", body: "오류 및 성능 개선 관련 업데이트를 반영했습니다." },
  { hash: "3ad8572", date: "2026-01-12", title: "기능 업데이트: 상세페이지 개선 및 이미지 추가", body: "상세페이지 개선 및 이미지 추가 관련 업데이트를 반영했습니다." },
  { hash: "cd2f512", date: "2026-01-07", title: "기능 업데이트: 컨텐츠 정보 최신화 보강", body: "컨텐츠 정보 최신화 보강 관련 업데이트를 반영했습니다." },
  { hash: "8546de4", date: "2026-01-06", title: "기능 업데이트: 상세페이지 개발 2차 진행", body: "상세페이지 개발 2차 진행 관련 업데이트를 반영했습니다." },
  { hash: "f6202e1", date: "2026-01-05", title: "기능 업데이트: 사용 안하는 파일 정리 및 메인화면, 상세페이지 1차 개발", body: "사용 안하는 파일 정리 및 메인화면, 상세페이지 1차 개발 관련 업데이트를 반영했습니다." },
  { hash: "60b886f", date: "2026-01-04", title: "기능 업데이트: 메인화면 ux ui 개선", body: "메인화면 ux ui 개선 관련 업데이트를 반영했습니다." },
  { hash: "95ced55", date: "2025-12-31", title: "기능 업데이트: 메인화면 캐러셀 개선", body: "메인화면 캐러셀 개선 관련 업데이트를 반영했습니다." },
  { hash: "46851ed", date: "2025-12-30", title: "기능 업데이트: header 정리 및 추천 재구성 1차", body: "header 정리 및 추천 재구성 1차 관련 업데이트를 반영했습니다." },
  { hash: "221ebf0", date: "2025-12-29", title: "기능 업데이트: 추가 api 연동 및 db 추가", body: "추가 api 연동 및 db 추가 관련 업데이트를 반영했습니다." },
  { hash: "16f0e75", date: "2025-12-29", title: "기능 업데이트: 로그인, 로그아웃 시 처리 개선", body: "로그인, 로그아웃 시 처리 개선 관련 업데이트를 반영했습니다." },
  { hash: "8e01bdd", date: "2025-12-29", title: "서비스 안정화: stop tracking generated prisma client", body: "stop tracking generated prisma client 관련 업데이트를 반영했습니다." },
  { hash: "18f87a0", date: "2025-12-28", title: "기능 업데이트: 메인페이지 footer 생성 및 이메일 인증 화면 사용성 개선", body: "메인페이지 footer 생성 및 이메일 인증 화면 사용성 개선 관련 업데이트를 반영했습니다." },
  { hash: "6a711ac", date: "2025-12-28", title: "기능 업데이트: 회원가입, 로그인 기능 구현 1차", body: "회원가입, 로그인 기능 구현 1차 관련 업데이트를 반영했습니다." },
  { hash: "8268011", date: "2025-12-27", title: "디자인 개선: 로그인, 회원가입 퍼블리싱 구현", body: "로그인, 회원가입 퍼블리싱 구현 관련 업데이트를 반영했습니다." },
  { hash: "0d24f2d", date: "2025-12-27", title: "기능 업데이트: 추천 알고리즘 보강", body: "추천 알고리즘 보강 관련 업데이트를 반영했습니다." },
  { hash: "edf90a2", date: "2025-12-21", title: "기능 업데이트: 추천 기능 업데이트", body: "추천 기능 업데이트 관련 업데이트를 반영했습니다." },
  { hash: "8312e3a", date: "2025-12-14", title: "기능 업데이트: 백엔드 전체적인 수정 및 알고리 즘, 카드 수정", body: "백엔드 전체적인 수정 및 알고리 즘, 카드 수정 관련 업데이트를 반영했습니다." },
  { hash: "8e485c7", date: "2025-12-14", title: "기능 업데이트: 백엔드 전체적인 수정 및 알고리즘, 카드 수정", body: "백엔드 전체적인 수정 및 알고리즘, 카드 수정 관련 업데이트를 반영했습니다." },
  { hash: "a7d58cc", date: "2025-12-14", title: "서비스 안정화: 추천 추가 및 전체적인 구조 수정", body: "추천 추가 및 전체적인 구조 수정 관련 업데이트를 반영했습니다." },
  { hash: "ce4af30", date: "2025-12-09", title: "서비스 업데이트: Update README.md", body: "Update README.md 관련 업데이트를 반영했습니다." },
  { hash: "26ba2e0", date: "2025-12-09", title: "서비스 업데이트: Update README.md", body: "Update README.md 관련 업데이트를 반영했습니다." },
  { hash: "f4831e0", date: "2025-12-09", title: "서비스 업데이트: Update README.md", body: "Update README.md 관련 업데이트를 반영했습니다." },
  { hash: "52e7294", date: "2025-12-09", title: "서비스 업데이트: Merge pull request #1 from yeongmins/develop", body: "Merge pull request #1 from yeongmins/develop 관련 업데이트를 반영했습니다." },
  { hash: "e5d6768", date: "2025-12-09", title: "서비스 안정화: fix vite outDir to dist", body: "fix vite outDir to dist 관련 업데이트를 반영했습니다." },
  { hash: "4703f7d", date: "2025-12-09", title: "문서 업데이트: 검색 엔진 + 메신저 썸네일 html 코드 수정", body: "검색 엔진 + 메신저 썸네일 html 코드 수정 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "2d0b988", date: "2025-12-09", title: "서비스 안정화: 백엔드 추가 이후 전체 파일 구조 업데이트", body: "백엔드 추가 이후 전체 파일 구조 업데이트 관련 업데이트를 반영했습니다." },
  { hash: "c790b1d", date: "2025-12-07", title: "서비스 안정화: unify and optimize .gitignore for monorepo", body: "unify and optimize .gitignore for monorepo 관련 업데이트를 반영했습니다." },
  { hash: "7ecf48b", date: "2025-12-07", title: "서비스 안정화: backend 폴더 NestJS 초기 세팅", body: "backend 폴더 NestJS 초기 세팅 관련 업데이트를 반영했습니다." },
  { hash: "29cba58", date: "2025-11-17", title: "오류 수정: 로고 아이콘 설정", body: "로고 아이콘 설정 관련 문제를 수정해 안정성을 높였습니다." },
  { hash: "871fccf", date: "2025-12-07", title: "서비스 안정화: 불필요 코드 ImageWithFallback 제거", body: "불필요 코드 ImageWithFallback 제거 관련 업데이트를 반영했습니다." },
  { hash: "5f30a61", date: "2025-12-07", title: "디자인 개선: 버튼 디자인 및 호버 수정", body: "버튼 디자인 및 호버 수정 관련 업데이트를 반영했습니다." },
  { hash: "3d6a7a3", date: "2025-12-07", title: "기능 업데이트: 모바일 속도 개선 및 온보딩 코드 리펙토링", body: "모바일 속도 개선 및 온보딩 코드 리펙토링 관련 업데이트를 반영했습니다." },
  { hash: "1826f99", date: "2025-12-05", title: "오류 수정: 새로고침 시 오류 해결", body: "새로고침 시 오류 해결 관련 문제를 수정해 안정성을 높였습니다." },
  { hash: "0cfa00e", date: "2025-12-05", title: "문서 업데이트: README 수정", body: "README 수정 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "02b2a7d", date: "2025-12-05", title: "오류 수정: 새로고침 시 오류발생으로 해결", body: "새로고침 시 오류발생으로 해결 관련 문제를 수정해 안정성을 높였습니다." },
  { hash: "30265af", date: "2025-12-04", title: "문서 업데이트: 주석 추가", body: "주석 추가 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "070cb05", date: "2025-12-02", title: "디자인 개선: 메인화면 영화 카드 디자인 오류 수정", body: "메인화면 영화 카드 디자인 오류 수정 관련 업데이트를 반영했습니다." },
  { hash: "9723d88", date: "2025-12-01", title: "디자인 개선: 로고 디자인 수정", body: "로고 디자인 수정 관련 업데이트를 반영했습니다." },
  { hash: "10e4943", date: "2025-12-01", title: "기능 업데이트: 디자인 디테일 및 반응형 수정", body: "디자인 디테일 및 반응형 수정 관련 업데이트를 반영했습니다." },
  { hash: "73446f8", date: "2025-11-23", title: "디자인 개선: 수정", body: "수정 관련 업데이트를 반영했습니다." },
  { hash: "57fdb26", date: "2025-11-22", title: "디자인 개선: 사이즈 조금 조절", body: "사이즈 조금 조절 관련 업데이트를 반영했습니다." },
  { hash: "c21f1e5", date: "2025-11-22", title: "기능 업데이트: 페이지 이동 추가 및 전체적인 화면 스타일 수정", body: "페이지 이동 추가 및 전체적인 화면 스타일 수정 관련 업데이트를 반영했습니다." },
  { hash: "9d45aad", date: "2025-11-21", title: "디자인 개선: 디자인 수정", body: "디자인 수정 관련 업데이트를 반영했습니다." },
  { hash: "d3d4839", date: "2025-11-18", title: "디자인 개선: 폰트 및 레이아웃 화면 스타일 수정", body: "폰트 및 레이아웃 화면 스타일 수정 관련 업데이트를 반영했습니다." },
  { hash: "69fc95a", date: "2025-11-18", title: "디자인 개선: 시작 버튼 사이즈 수정", body: "시작 버튼 사이즈 수정 관련 업데이트를 반영했습니다." },
  { hash: "bd824d3", date: "2025-11-18", title: "오류 수정: 이전 버튼 수정", body: "이전 버튼 수정 관련 문제를 수정해 안정성을 높였습니다." },
  { hash: "e6127ff", date: "2025-11-18", title: "구조 개선: 디자인 위주로 수정", body: "디자인 위주로 수정 관련 업데이트를 반영했습니다." },
  { hash: "2f95d35", date: "2025-11-17", title: "문서 업데이트: HTML 수정", body: "HTML 수정 내용을 최신 기준에 맞게 정리했습니다." },
  { hash: "b9fb89a", date: "2025-11-17", title: "오류 수정: 로고 아이콘 설정", body: "로고 아이콘 설정 관련 문제를 수정해 안정성을 높였습니다." },
  { hash: "8c8622f", date: "2025-11-17", title: "서비스 업데이트: Revise README with updated project details", body: "Revise README with updated project details 관련 업데이트를 반영했습니다." },
  { hash: "5639371", date: "2025-11-17", title: "기능 업데이트: 여러가지 기능 추가 및 오류 수정", body: "여러가지 기능 추가 및 오류 수정 관련 업데이트를 반영했습니다." },
  { hash: "b21823f", date: "2025-11-16", title: "서비스 업데이트: Update project description in README.md", body: "Update project description in README.md 관련 업데이트를 반영했습니다." },
  { hash: "407e054", date: "2025-11-16", title: "서비스 업데이트: PickMovie 1.0 완료", body: "PickMovie 1.0 완료 관련 업데이트를 반영했습니다." },
  { hash: "2e46170", date: "2025-11-15", title: "서비스 업데이트: Add files from Figma Make", body: "Add files from Figma Make 관련 업데이트를 반영했습니다." },
  { hash: "1e6a269", date: "2025-11-15", title: "서비스 업데이트: Initial commit", body: "Initial commit 관련 업데이트를 반영했습니다." },
];
